import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authenticate } from "./auth.js";
import { requiresApproval, validateBranchName } from "./github-write-policy.js";

type AuthPayload = { sub: string; tenantId: string; role: string };
export type GitHubRepository = { owner: string; name: string; defaultBranch?: string };
export type GitHubFileChange = { path: string; content: string };
export type GitHubCIStatus = { state: string; statuses?: unknown[]; sha?: string };
export type GitHubCIJob = { id: number; name?: string; status?: string; conclusion?: string; url?: string };
export type GitHubClient = { getRepository(repository: GitHubRepository): Promise<unknown>; listBranches(repository: GitHubRepository): Promise<unknown[]>; getFile(repository: GitHubRepository, path: string, ref?: string): Promise<unknown>; createBranch(repository: GitHubRepository, branch: string, fromRef?: string): Promise<unknown>; commitChanges(repository: GitHubRepository, branch: string, message: string, changes: GitHubFileChange[]): Promise<unknown>; push(repository: GitHubRepository, branch: string, message: string, changes: GitHubFileChange[]): Promise<unknown>; createPullRequest(repository: GitHubRepository, title: string, head: string, base: string, body?: string): Promise<unknown>; getCommitStatus?(repository: GitHubRepository, sha: string): Promise<GitHubCIStatus>; listWorkflowRunsForCommit?(repository: GitHubRepository, sha: string): Promise<unknown[]>; listWorkflowJobs?(repository: GitHubRepository, runId: number): Promise<GitHubCIJob[]>; getWorkflowJobLogs?(repository: GitHubRepository, jobId: number): Promise<string> };
export class GitHubProviderRegistry { private client?: GitHubClient; setClient(client: GitHubClient): void { this.client = client; } getClient(): GitHubClient { if (!this.client) throw new Error("GitHub integration is not configured"); return this.client; } configured(): boolean { return Boolean(this.client); } }
export const githubRegistry = new GitHubProviderRegistry();
const repoSchema = z.object({ owner: z.string().regex(/^[A-Za-z0-9_.-]+$/), name: z.string().regex(/^[A-Za-z0-9_.-]+$/), defaultBranch: z.string().optional() });
const changesSchema = z.array(z.object({ path: z.string().min(1).max(1000), content: z.string().max(2_000_000) })).min(1).max(100);
const developerRoles = new Set(["OWNER", "ADMIN", "DEVELOPER"]);
function protectedBranch(branch: string, defaultBranch?: string): boolean { return new Set(["main", "master", "production", "prod", defaultBranch].filter(Boolean)).has(branch); }
function returnedSha(value: unknown): string | undefined { if (!value || typeof value !== "object") return undefined; const object = value as Record<string, unknown>; return typeof object.sha === "string" ? object.sha : typeof object.commitSha === "string" ? object.commitSha : typeof object.commit?.sha === "string" ? object.commit.sha : undefined; }
async function verifyReadBack(client: GitHubClient, repository: GitHubRepository, branch: string, changes: GitHubFileChange[]): Promise<{ verified: boolean; files: string[] }> { const verified: string[] = []; for (const change of changes) { const result = await client.getFile(repository, change.path, branch); const raw = typeof result === "string" ? result : result && typeof result === "object" && typeof (result as Record<string, unknown>).content === "string" ? (result as Record<string, unknown>).content : undefined; if (raw === undefined || raw !== change.content) throw new Error(`GitHub read-back verification failed for ${change.path}`); verified.push(change.path); } return { verified: verified.length === changes.length, files: verified }; }

export async function registerGitHubAgentRoutes(app: FastifyInstance): Promise<void> {
  app.get("/api/v1/github/status", { preHandler: authenticate }, async request => { const auth = request.user as AuthPayload; return { configured: githubRegistry.configured(), tenantId: auth.tenantId, capabilities: ["repository.read", "branch.read", "file.read", "branch.create", "commit", "push", "pull_request", "ci.read", "ci.diagnostics"] }; });
  app.post("/api/v1/github/ci", { preHandler: authenticate }, async (request, reply) => { const input = repoSchema.extend({ sha: z.string().regex(/^[0-9a-fA-F]{7,64}$/) }).parse(request.body); const client = githubRegistry.getClient(); if (!client.getCommitStatus) return reply.code(503).send({ error: "GitHub CI status provider is not configured", verified: false }); try { const status = await client.getCommitStatus(input, input.sha); const runs = client.listWorkflowRunsForCommit ? await client.listWorkflowRunsForCommit(input, input.sha) : []; const diagnostics: Array<Record<string, unknown>> = []; if (client.listWorkflowJobs) { for (const run of runs) { const runObject = run as Record<string, unknown>; const runId = typeof runObject.id === "number" ? runObject.id : undefined; if (runId === undefined) continue; const jobs = await client.listWorkflowJobs(input, runId); for (const job of jobs) { const failed = ["failure", "cancelled", "timed_out", "action_required"].includes(String(job.conclusion ?? "").toLowerCase()); if (failed) { const steps = client.getWorkflowJobLogs ? await client.getWorkflowJobLogs(input, job.id) : undefined; diagnostics.push({ runId, jobId: job.id, jobName: job.name, status: job.status, conclusion: job.conclusion, log: steps?.slice(0, 20_000) }); } } } } const state = String(status.state ?? "unknown").toLowerCase(); const verified = ["success", "failure", "error", "pending"].includes(state) || runs.length > 0; return reply.send({ status, runs, diagnostics, evidence: { type: "GITHUB_CI", commitSha: input.sha, state, verified, diagnosticEvidence: diagnostics.length > 0 } }); } catch (error) { return reply.code(503).send({ error: error instanceof Error ? error.message : "GitHub CI inspection failed", verified: false }); } });
  app.post("/api/v1/github/repository", { preHandler: authenticate }, async (request, reply) => { const input = repoSchema.parse(request.body); try { return reply.send(await githubRegistry.getClient().getRepository(input)); } catch (error) { return reply.code(503).send({ error: error instanceof Error ? error.message : "GitHub integration unavailable" }); } });
  app.post("/api/v1/github/branches", { preHandler: authenticate }, async (request, reply) => { const input = repoSchema.parse(request.body); try { return reply.send(await githubRegistry.getClient().listBranches(input)); } catch (error) { return reply.code(503).send({ error: error instanceof Error ? error.message : "GitHub integration unavailable" }); } });
  app.post("/api/v1/github/file", { preHandler: authenticate }, async (request, reply) => { const input = repoSchema.extend({ path: z.string().min(1).max(1000), ref: z.string().max(200).optional() }).parse(request.body); try { return reply.send(await githubRegistry.getClient().getFile(input, input.path, input.ref)); } catch (error) { return reply.code(503).send({ error: error instanceof Error ? error.message : "GitHub integration unavailable" }); } });
  app.post("/api/v1/github/branch", { preHandler: authenticate }, async (request, reply) => { const input = repoSchema.extend({ branch: z.string().regex(/^[A-Za-z0-9._/-]+$/).max(200), fromRef: z.string().max(200).optional(), approved: z.boolean().default(false) }).parse(request.body); const auth = request.user as AuthPayload; if (!developerRoles.has(auth.role)) return reply.code(403).send({ error: "GitHub branch creation requires developer permissions" }); try { validateBranchName(input.branch); if (protectedBranch(input.branch, input.defaultBranch)) return reply.code(403).send({ error: "Protected branches require a pull request workflow" }); if (requiresApproval("CREATE_BRANCH", input.branch) && !input.approved) return reply.code(409).send({ status: "WAITING_APPROVAL", requiresApproval: true, action: "CREATE_BRANCH" }); return reply.code(201).send(await githubRegistry.getClient().createBranch(input, input.branch, input.fromRef)); } catch (error) { return reply.code(503).send({ error: error instanceof Error ? error.message : "GitHub branch creation failed" }); } });
  app.post("/api/v1/github/commit", { preHandler: authenticate }, async (request, reply) => { const input = repoSchema.extend({ branch: z.string().min(1).max(200), message: z.string().min(1).max(500), changes: changesSchema, approved: z.boolean().default(false) }).parse(request.body); const auth = request.user as AuthPayload; if (!developerRoles.has(auth.role)) return reply.code(403).send({ error: "Developer permission required" }); try { validateBranchName(input.branch); if (protectedBranch(input.branch, input.defaultBranch)) return reply.code(403).send({ error: "Protected branches require a pull request workflow" }); if (requiresApproval("COMMIT", input.branch) && !input.approved) return reply.code(409).send({ status: "WAITING_APPROVAL", requiresApproval: true, action: "COMMIT", branch: input.branch, files: input.changes.map(c => c.path) }); const client = githubRegistry.getClient(); const result = await client.commitChanges(input, input.branch, input.message, input.changes); const verification = await verifyReadBack(client, input, input.branch, input.changes); return reply.send({ result, evidence: { type: "GITHUB_READ_BACK", ...verification, commitSha: returnedSha(result) } }); } catch (error) { return reply.code(503).send({ error: error instanceof Error ? error.message : "GitHub commit failed", verified: false }); } });
  app.post("/api/v1/github/push", { preHandler: authenticate }, async (request, reply) => { const input = repoSchema.extend({ branch: z.string().min(1).max(200), message: z.string().min(1).max(500), changes: changesSchema, approved: z.boolean().default(false) }).parse(request.body); const auth = request.user as AuthPayload; if (!developerRoles.has(auth.role)) return reply.code(403).send({ error: "Developer permission required" }); try { validateBranchName(input.branch); if (protectedBranch(input.branch, input.defaultBranch)) return reply.code(403).send({ error: "Protected branches require a pull request workflow" }); if (requiresApproval("PUSH", input.branch) && !input.approved) return reply.code(409).send({ status: "WAITING_APPROVAL", requiresApproval: true, action: "PUSH", branch: input.branch, files: input.changes.map(c => c.path) }); const client = githubRegistry.getClient(); const result = await client.push(input, input.branch, input.message, input.changes); const verification = await verifyReadBack(client, input, input.branch, input.changes); return reply.send({ result, evidence: { type: "GITHUB_READ_BACK", ...verification, commitSha: returnedSha(result) } }); } catch (error) { return reply.code(503).send({ error: error instanceof Error ? error.message : "GitHub push failed", verified: false }); } });
  app.post("/api/v1/github/pr", { preHandler: authenticate }, async (request, reply) => { const input = repoSchema.extend({ title: z.string().min(1).max(300), head: z.string().min(1).max(200), base: z.string().min(1).max(200), body: z.string().max(20_000).optional(), approved: z.boolean().default(false) }).parse(request.body); const auth = request.user as AuthPayload; if (!developerRoles.has(auth.role)) return reply.code(403).send({ error: "Developer permission required" }); if (input.head === input.base) return reply.code(400).send({ error: "Pull request head and base must differ" }); if (protectedBranch(input.base, input.defaultBranch) && !input.approved) return reply.code(409).send({ status: "WAITING_APPROVAL", requiresApproval: true, action: "CREATE_PR", base: input.base }); if (!input.approved) return reply.code(409).send({ status: "WAITING_APPROVAL", requiresApproval: true, action: "CREATE_PR" }); try { return reply.code(201).send(await githubRegistry.getClient().createPullRequest(input, input.title, input.head, input.base, input.body)); } catch (error) { return reply.code(503).send({ error: error instanceof Error ? error.message : "Pull request creation failed" }); } });
}
