import { z } from "zod";
import { toolRegistry } from "./tools.js";
import { githubRegistry } from "./github-agent.js";

const repo = z.object({ owner: z.string().regex(/^[A-Za-z0-9_.-]+$/), name: z.string().regex(/^[A-Za-z0-9_.-]+$/), defaultBranch: z.string().optional() });
const changes = z.array(z.object({ path: z.string().min(1).max(1000), content: z.string().max(2_000_000) })).min(1).max(100);
const branch = z.string().min(1).max(200).refine(value => !value.startsWith("-"), "Invalid branch name");

function assertWritableBranch(value: string, defaultBranch?: string): void { const protectedNames = new Set([defaultBranch, "main", "master", "production", "prod"].filter(Boolean)); if (protectedNames.has(value)) throw new Error("Direct writes to protected branches are not allowed; create/use a working branch and PR"); }
function readContent(value: unknown): string | null { if (typeof value === "string") return value; if (value && typeof value === "object" && "content" in value && typeof (value as { content?: unknown }).content === "string") return (value as { content: string }).content; return null; }
function commitShaFrom(value: unknown): string | undefined { if (!value || typeof value !== "object") return undefined; const object = value as Record<string, unknown>; return typeof object.sha === "string" ? object.sha : typeof object.commitSha === "string" ? object.commitSha : undefined; }
async function verifyChanges(input: { owner: string; name: string; defaultBranch?: string; branch: string; changes: Array<{ path: string; content: string }> }, operation: string, result: unknown) {
  const client = githubRegistry.getClient();
  const checks = await Promise.all(input.changes.map(async change => { try { const observed = await client.getFile(input, change.path, input.branch); const content = readContent(observed); return { path: change.path, verified: content === change.content }; } catch { return { path: change.path, verified: false }; } }));
  const verified = checks.length > 0 && checks.every(check => check.verified);
  return { operation, verified, commitSha: commitShaFrom(result), files: checks };
}

export function registerGitHubCodingTools(): void {
  if (!toolRegistry.get("github.inspect")) toolRegistry.register({ name: "github.inspect", description: "Inspect a GitHub repository, branches, and explicitly requested files.", inputSchema: repo.extend({ ref: z.string().optional(), paths: z.array(z.string()).max(50).default([]) }), risk: "LOW", permissions: ["GITHUB_READ"], timeoutMs: 60_000, execute: async input => { const client = githubRegistry.getClient(); const repository = await client.getRepository(input); const branches = await client.listBranches(input); const files = await Promise.all(input.paths.map(async path => ({ path, content: await client.getFile(input, path, input.ref ?? input.defaultBranch) }))); return { repository, branches, files }; } });
  if (!toolRegistry.get("github.commit")) toolRegistry.register({ name: "github.commit", description: "Create a Git commit from supplied file changes on a working branch. Requires explicit approval.", inputSchema: repo.extend({ branch, message: z.string().min(1).max(500), changes }), risk: "HIGH", permissions: ["GITHUB_WRITE"], timeoutMs: 120_000, execute: async input => { assertWritableBranch(input.branch, input.defaultBranch); const result = await githubRegistry.getClient().commitChanges(input, input.branch, input.message, input.changes); return { result, evidence: await verifyChanges(input, "COMMIT_READ_BACK", result) }; } });
  if (!toolRegistry.get("github.push")) toolRegistry.register({ name: "github.push", description: "Push supplied changes to an existing working GitHub branch. Requires explicit approval and push permission.", inputSchema: repo.extend({ branch, message: z.string().min(1).max(500), changes }), risk: "CRITICAL", permissions: ["GITHUB_PUSH"], timeoutMs: 120_000, execute: async input => { assertWritableBranch(input.branch, input.defaultBranch); const result = await githubRegistry.getClient().push(input, input.branch, input.message, input.changes); return { result, evidence: await verifyChanges(input, "PUSH_READ_BACK", result) }; } });
  if (!toolRegistry.get("github.ci_status")) toolRegistry.register({ name: "github.ci_status", description: "Read GitHub commit CI status. Returns PENDING while checks are running, SUCCESS only when GitHub reports success, and FAILURE for failure/error states.", inputSchema: repo.extend({ commitSha: z.string().regex(/^[0-9a-fA-F]{7,64}$/) }), risk: "LOW", permissions: ["GITHUB_READ"], timeoutMs: 60_000, execute: async input => { const client = githubRegistry.getClient(); if (!client.getCommitStatus) throw new Error("GitHub CI status integration is not configured"); const raw = await client.getCommitStatus(input, input.commitSha); const data = raw && typeof raw === "object" ? raw as Record<string, unknown> : {}; const state = typeof data.state === "string" ? data.state.toLowerCase() : "pending"; const normalized = state === "success" ? "SUCCESS" : state === "failure" || state === "error" ? "FAILURE" : "PENDING"; return { status: normalized, commitSha: input.commitSha, evidence: { type: "GITHUB_COMMIT_STATUS", state, totalCount: typeof data.total_count === "number" ? data.total_count : undefined, checks: Array.isArray(data.statuses) ? data.statuses.map((check: unknown) => { const item = check && typeof check === "object" ? check as Record<string, unknown> : {}; return { context: item.context, state: item.state, description: item.description, targetUrl: item.target_url }; }) : [] } }; } });
  if (!toolRegistry.get("github.create_pr")) toolRegistry.register({ name: "github.create_pr", description: "Create a GitHub pull request from a prepared working branch. Requires explicit approval.", inputSchema: repo.extend({ branch: z.string().min(1).max(200), title: z.string().min(1).max(300), head: z.string().min(1).max(200), base: z.string().min(1).max(200), body: z.string().max(20_000).optional() }), risk: "HIGH", permissions: ["PR_CREATE"], timeoutMs: 60_000, execute: async input => { if (input.head === input.base) throw new Error("Pull request head and base must differ"); return githubRegistry.getClient().createPullRequest(input, input.title, input.head, input.base, input.body); } });
}
