import Fastify from "fastify";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import jwt from "@fastify/jwt";
import { registerAuthRoutes } from "./auth.js";
import { registerProjectRoutes } from "./projects.js";
import { registerConversationRoutes } from "./conversations.js";
import { registerChatRoutes } from "./chat.js";
import { registerChatStreamRoutes } from "./chat-stream.js";
import { registerAgentRoutes } from "./agent.js";
import { registerPermissionRoutes } from "./permissions.js";
import { registerWorkspaceRoutes } from "./workspace.js";
import { registerCodingRoutes, registerCodingTools } from "./coding.js";
import { registerCodeAgentRoutes } from "./code-agent.js";
import { registerTerminalTool } from "./terminal.js";
import { registerGitHubAgentRoutes, githubRegistry } from "./github-agent.js";
import { registerGitHubWriteRoutes } from "./github-write.js";
import { registerGitHubActionRoutes } from "./github-actions.js";
import { registerGitHubCodingAgentRoutes } from "./github-coding-agent.js";
import { registerGitHubExecutionRoutes } from "./github-execution.js";
import { registerGitHubCodingTools } from "./github-tools.js";
import { registerResearchRoutes, registerResearchTools } from "./research.js";
import { registerContextRoutes } from "./context.js";
import { registerCiFailureRoutes } from "./ci-failure-route.js";
import { registerCiRepairRoutes } from "./ci-repair-route.js";
import { GitHubHttpClient } from "./github-client.js";
import { toolRegistry } from "./tools.js";
import { modelRouterInfo } from "./model-router.js";
import { providerHealthSnapshot } from "./model-health.js";
import { runtimeMetrics } from "./runtime-metrics.js";
import { db } from "./db.js";
import { taskQueue } from "./task-queue.js";
import { processTaskQueueItem } from "./task-worker.js";
import { startQueueRecovery, stopQueueRecovery } from "./queue-recovery.js";

const app = Fastify({ logger: true });
await app.register(helmet);
await app.register(cors, { origin: process.env.CORS_ORIGIN ?? "http://localhost:5173", credentials: true });
const jwtSecret = process.env.JWT_SECRET;
if (!jwtSecret || jwtSecret.length < 32) throw new Error("JWT_SECRET must be configured and at least 32 characters long");
await app.register(jwt, { secret: jwtSecret });
registerCodingTools(); registerTerminalTool(); registerGitHubCodingTools(); registerResearchTools();
if (process.env.GITHUB_TOKEN) githubRegistry.setClient(new GitHubHttpClient(process.env.GITHUB_TOKEN));
app.get("/health", async () => ({ status: "ok", service: "ynaiudan-api", version: "0.1.0" }));
app.get("/health/database", async (_request, reply) => { try { await db.$runCommandRaw({ ping: 1 }); return { status: "ok", service: "mongodb" }; } catch { return reply.code(503).send({ status: "unavailable", service: "mongodb" }); } });
app.get("/health/readiness", async (_request, reply) => { try { await db.$runCommandRaw({ ping: 1 }); return { status: "ready", database: "ok", queue: { size: await taskQueue.size(), activeWorkers: taskQueue.activeWorkers() }, models: modelRouterInfo(), providers: providerHealthSnapshot() }; } catch { return reply.code(503).send({ status: "not_ready", database: "unavailable" }); } });
app.get("/api/v1", async () => ({ name: "YnAiUdan API", version: "v1" }));
app.get("/api/v1/tools", async () => toolRegistry.list());
app.get("/api/v1/models", async () => modelRouterInfo());
app.get("/api/v1/metrics", async () => runtimeMetrics());
app.get("/api/v1/provider-health", async () => providerHealthSnapshot());
await registerAuthRoutes(app); await registerProjectRoutes(app); await registerConversationRoutes(app); await registerChatRoutes(app); await registerChatStreamRoutes(app); await registerAgentRoutes(app); await registerPermissionRoutes(app); await registerWorkspaceRoutes(app); await registerCodingRoutes(app); await registerCodeAgentRoutes(app); await registerGitHubAgentRoutes(app); await registerGitHubWriteRoutes(app); await registerGitHubActionRoutes(app); await registerGitHubCodingAgentRoutes(app); await registerGitHubExecutionRoutes(app); await registerResearchRoutes(app); await registerContextRoutes(app); await registerCiFailureRoutes(app); await registerCiRepairRoutes(app);
startQueueRecovery();
void taskQueue.start(processTaskQueueItem);
const shutdown = async () => { stopQueueRecovery(); taskQueue.stop(); await db.$disconnect(); await app.close(); };
process.once("SIGTERM", () => void shutdown()); process.once("SIGINT", () => void shutdown());
const port = Number(process.env.PORT ?? 4000); const host = process.env.HOST ?? "0.0.0.0";
try { await app.listen({ port, host }); } catch (error) { app.log.error(error); await db.$disconnect(); process.exit(1); }
