import { db } from "./db.js";
import { executeTool } from "./tool-executor.js";
import { saveTaskMemory } from "./memory-service.js";
import { findLearning, markLearningOutcome, promoteVerifiedTaskLearning, recordLearning } from "./learning-service.js";
import { captureRegressionLesson } from "./regression-learning.js";
import { recordArtifact } from "./artifact-ledger.js";
import { getExecutionLedger } from "./universal-execution-ledger.js";
import { verifyBeforeRelease } from "./agent-verification-gate.js";

function compactMemoryValue(value: unknown): string { try { const text = typeof value === "string" ? value : JSON.stringify(value); return text.slice(0, 9000); } catch { return String(value).slice(0, 9000); } }
async function persistExecutionMemory(task: { id: string; tenantId: string; userId: string; projectId: string | null; title: string; goal: string }, input: { toolName: string; input?: unknown }, result: { ok: boolean; output?: unknown; error?: string; tool?: string }) { const toolName = result.tool ?? input.toolName; const status = result.ok ? "SUCCESS" : "FAILURE"; const value = result.ok ? `Task: ${task.title}\nGoal: ${task.goal}\nTool: ${toolName}\nInput: ${compactMemoryValue(input.input)}\nResult: ${compactMemoryValue(result.output)}` : `Task: ${task.title}\nGoal: ${task.goal}\nTool: ${toolName}\nInput: ${compactMemoryValue(input.input)}\nFailure: ${result.error ?? "Unknown tool failure"}`; await saveTaskMemory({ tenantId: task.tenantId, userId: task.userId, projectId: task.projectId ?? undefined, taskId: task.id, key: `tool:${toolName}:${status.toLowerCase()}`, value, importance: result.ok ? 0.75 : 0.85 }); }
async function captureLearning(task: { tenantId: string; userId: string; projectId: string | null; goal: string }, input: { toolName: string; input?: unknown }, result: { ok: boolean; output?: unknown; error?: string; tool?: string }, verification?: unknown) { const tool = result.tool ?? input.toolName; await recordLearning({ tenantId: task.tenantId, userId: task.userId, projectId: task.projectId ?? undefined, query: task.goal, kind: result.ok ? "SOLUTION" : "MISTAKE", solution: result.ok ? `Tool ${tool} succeeded. Result: ${compactMemoryValue(result.output)}` : undefined, mistake: result.ok ? undefined : `Tool ${tool} failed: ${result.error ?? "Unknown failure"}`, rootCause: result.ok ? undefined : "Execution failure; root cause requires subsequent analysis", verification: compactMemoryValue(verification ?? (result.ok ? result.output : result.error)), verified: false, confidence: result.ok ? 0.6 : 0.35 }).catch(() => undefined); }
async function attributeLearningOutcome(task: { tenantId: string; userId: string; projectId: string | null; goal: string }, toolName: string, lessons: Array<{ id: string; normalizedQuery: string; solution: string | null; correction: string | null }>, success: boolean, verification: unknown) { const toolText = `${task.goal} ${toolName}`.toLowerCase(); const relevant = lessons.filter(lesson => { const text = `${lesson.normalizedQuery} ${lesson.solution ?? ""} ${lesson.correction ?? ""}`.toLowerCase(); const terms = toolText.split(/\s+/).filter(term => term.length >= 4).slice(0, 30); return terms.filter(term => text.includes(term)).length >= 2; }).slice(0, 5); await Promise.all(relevant.map(lesson => markLearningOutcome({ id: lesson.id, tenantId: task.tenantId, userId: task.userId, success, verification: compactMemoryValue(verification) }).catch(() => undefined))); }
async function captureRegressionIfRecovered(task: { id: string; tenantId: string; userId: string; projectId: string | null; goal: string }, stepId: string, input: { toolName: string; input?: unknown; previousFailureLessons?: unknown[] }, result: { ok: boolean; output?: unknown; error?: string; tool?: string }, verification?: unknown) { if (!result.ok || !Array.isArray(input.previousFailureLessons) || input.previousFailureLessons.length === 0) return; const lessons = input.previousFailureLessons.slice(0, 3).map((lesson: unknown) => { const item = lesson && typeof lesson === "object" ? lesson as Record<string, unknown> : {}; return `mistake=${String(item.mistake ?? "unknown")}; rootCause=${String(item.rootCause ?? "unknown")}`; }).join("\n"); await captureRegressionLesson({ taskId: task.id, stepId, tenantId: task.tenantId, userId: task.userId, projectId: task.projectId, goal: task.goal, failure: lessons, correction: `Recovered with tool ${result.tool ?? input.toolName}: ${compactMemoryValue(result.output)}`, verification: compactMemoryValue(verification ?? result.output) }).catch(() => undefined); }
function evidenceObject(output: unknown): Record<string, unknown> | undefined { if (!output || typeof output !== "object") return undefined; const evidence = (output as Record<string, unknown>).evidence; return evidence && typeof evidence === "object" ? evidence as Record<string, unknown> : undefined; }
function verifiedGitHubWrite(toolName: string, output: unknown): boolean { if (!["github.commit", "github.push"].includes(toolName)) return true; return evidenceObject(output)?.verified === true; }
function verifiedCI(toolName: string, output: unknown): boolean { if (toolName !== "github.ci_status") return true; const evidence = evidenceObject(output); return evidence?.type === "GITHUB_COMMIT_STATUS" && output && typeof output === "object" && (output as Record<string, unknown>).status === "SUCCESS"; }
function verificationSummary(toolName: string, output: unknown): Record<string, unknown> { const evidence = evidenceObject(output); if (toolName === "github.ci_status") return { verified: (output as Record<string, unknown>).status === "SUCCESS", type: evidence?.type ?? "GITHUB_COMMIT_STATUS", commitSha: evidence?.commitSha, state: evidence?.state }; if (evidence) return { verified: evidence.verified !== false, type: evidence.type, commitSha: evidence.commitSha, files: evidence.files }; return { verified: true, type: "TOOL_EXECUTION", reason: "Tool returned successfully" }; }

export async function executeNextTaskStep(taskId: string, userId: string, tenantId: string, role: string, requestedStepId?: string) {
  const task = await db.task.findFirst({ where: { id: taskId, userId, tenantId }, include: { steps: { orderBy: { sequence: "asc" } } } }); if (!task) throw new Error("Task not found"); if (task.status !== "RUNNING") throw new Error(`Task is not executable in ${task.status} state`);
  const completed = task.steps.filter(step => step.status === "COMPLETED").length; if (task.maxSteps !== null && completed >= task.maxSteps) { await db.task.update({ where: { id: task.id }, data: { status: "PAUSED" } }); return { status: "PAUSED", reason: "MAX_STEPS_REACHED" }; }
  const completedToolCalls = task.steps.filter(step => step.name === "TOOL" && step.status === "COMPLETED").length; if (task.maxToolCalls !== null && completedToolCalls >= task.maxToolCalls) { await db.task.update({ where: { id: task.id }, data: { status: "PAUSED" } }); return { status: "PAUSED", reason: "MAX_TOOL_CALLS_REACHED" }; }
  const pending = task.steps.find(candidate => candidate.status === "PENDING" && (!requestedStepId || candidate.id === requestedStepId));
  if (!pending) {
    const completedSteps = task.steps.filter(step => step.status === "COMPLETED");
    const ledger = await getExecutionLedger(task.id, task.tenantId);
    const artifacts = await db.artifact.findMany({ where: { taskId: task.id, tenantId: task.tenantId }, select: { path: true, sha256: true, verificationStatus: true } });
    const gate = verifyBeforeRelease({ goal: task.goal, steps: completedSteps.map(step => ({ id: step.id, status: step.status, output: step.output, error: step.error })), artifacts, evidence: ledger.events.map(event => ({ kind: event.kind, summary: event.summary, data: event.data })) });
    if (!gate.passed) return { status: "FAILED", reason: "VERIFICATION_GATE_BLOCKED", verification: gate };
    await promoteVerifiedTaskLearning({ tenantId: task.tenantId, userId: task.userId, projectId: task.projectId, goal: task.goal, verification: compactMemoryValue(gate) }).catch(() => undefined);
    await db.task.update({ where: { id: task.id }, data: { status: "COMPLETED" } });
    return { status: "COMPLETED", verification: gate };
  }
  const claimed = await db.taskStep.updateMany({ where: { id: pending.id, taskId: task.id, status: "PENDING" }, data: { status: "RUNNING", startedAt: new Date() } }); if (claimed.count !== 1) return { status: "RUNNING", reason: "STEP_ALREADY_CLAIMED", stepId: pending.id }; const step = pending;
  if (step.name !== "TOOL") { await db.taskStep.update({ where: { id: step.id }, data: { status: "COMPLETED", completedAt: new Date(), output: { acknowledged: true, verification: { verified: true, type: "CONTROL_STEP" } } } }); return { status: "COMPLETED", stepId: step.id, next: true }; }
  const input = (step.input ?? {}) as { toolName?: string; input?: unknown; approvalGranted?: boolean; previousFailureLessons?: unknown[] }; if (!input.toolName) { await db.taskStep.update({ where: { id: step.id }, data: { status: "FAILED", error: "Tool step is missing toolName", completedAt: new Date() } }); return { status: "FAILED", stepId: step.id, error: "Tool step is missing toolName" }; }
  const learningCandidates = await findLearning(`${task.goal} ${input.toolName}`, { tenantId: task.tenantId, userId: task.userId, projectId: task.projectId ?? undefined, limit: 5 }).catch(() => []);
  const result = await executeTool({ toolName: input.toolName, input: input.input, tenantId: task.tenantId, role, mode: task.autonomyMode, approvalGranted: input.approvalGranted === true });
  if (result.ok) { const verified = verifiedGitHubWrite(input.toolName, result.output) && verifiedCI(input.toolName, result.output); if (!verified) { const reason = input.toolName === "github.ci_status" ? "CI did not reach SUCCESS" : "Repository write completed without verified read-back evidence"; const verification = verificationSummary(input.toolName, result.output); await db.taskStep.update({ where: { id: step.id }, data: { status: "FAILED", error: reason, completedAt: new Date(), output: { result: result.output, verification } } }); await db.task.update({ where: { id: task.id }, data: { status: "FAILED" } }); await persistExecutionMemory(task, input as { toolName: string; input?: unknown }, { ok: false, tool: input.toolName, error: reason }); await captureLearning(task, input as { toolName: string; input?: unknown }, { ok: false, tool: input.toolName, error: reason }, verification); await attributeLearningOutcome(task, input.toolName, learningCandidates, false, verification); return { status: "FAILED", stepId: step.id, tool: input.toolName, error: reason, verification }; }
    let artifact: unknown;
    if (input.toolName === "workspace.write") {
      const artifactInput = input.input && typeof input.input === "object" ? input.input as Record<string, unknown> : {};
      const path = typeof artifactInput.path === "string" ? artifactInput.path : undefined;
      const content = typeof artifactInput.content === "string" ? artifactInput.content : undefined;
      if (!path || content === undefined) { const reason = "Workspace artifact missing path or content for provenance recording"; await db.taskStep.update({ where: { id: step.id }, data: { status: "FAILED", error: reason, completedAt: new Date(), output: { result: result.output, verification: { verified: false, reason } } } }); await db.task.update({ where: { id: task.id }, data: { status: "FAILED" } }); return { status: "FAILED", stepId: step.id, tool: input.toolName, error: reason }; }
      artifact = await recordArtifact({ taskId: task.id, tenantId: task.tenantId, userId: task.userId, artifactType: "FILE", name: path.split("/").pop() ?? path, path, content, tool: input.toolName, sourceStepId: step.id, verificationStatus: "EXECUTION_VERIFIED", provenance: { goal: task.goal, model: task.model, taskId: task.id } });
    }
    const verification = verificationSummary(input.toolName, result.output);
    const output = artifact ? { result: result.output, verification, artifact } : { result: result.output, verification };
    await db.taskStep.update({ where: { id: step.id }, data: { status: "COMPLETED", output, completedAt: new Date() } }); await persistExecutionMemory(task, input as { toolName: string; input?: unknown }, result); await captureLearning(task, input as { toolName: string; input?: unknown }, result, verification); await captureRegressionIfRecovered(task, step.id, input, result, verification); await attributeLearningOutcome(task, input.toolName, learningCandidates, true, verification); return { status: "COMPLETED", stepId: step.id, tool: result.tool, output: result.output, verification, ...(artifact ? { artifact } : {}) }; }
  if (result.requiresApproval) { await db.taskStep.update({ where: { id: step.id }, data: { status: "PENDING", startedAt: null } }); await db.task.update({ where: { id: task.id }, data: { status: "WAITING_APPROVAL" } }); return { status: "WAITING_APPROVAL", stepId: step.id, tool: result.tool, error: result.error }; }
  await db.taskStep.update({ where: { id: step.id }, data: { status: "FAILED", error: result.error, completedAt: new Date() } }); await db.task.update({ where: { id: task.id }, data: { status: "FAILED" } }); await persistExecutionMemory(task, input as { toolName: string; input?: unknown }, result); await captureLearning(task, input as { toolName: string; input?: unknown }, result); await attributeLearningOutcome(task, input.toolName, learningCandidates, false, result.error); return { status: "FAILED", stepId: step.id, tool: result.tool, error: result.error };
}
