import { db } from "./db.js";
import type { QueueJob, TaskQueueBackend } from "./task-queue-backend.js";

export class MongoTaskQueueBackend implements TaskQueueBackend {
  async enqueue(taskId: string): Promise<QueueJob> { const task = await db.task.findUnique({ where: { id: taskId }, select: { id: true, tenantId: true, status: true } }); if (!task) throw new Error("Task not found"); if (["CANCELLED", "COMPLETED"].includes(task.status)) throw new Error(`Cannot enqueue task in ${task.status} state`); const existing = await db.taskQueueJob.findFirst({ where: { taskId: task.id, status: { in: ["QUEUED", "RUNNING"] } }, select: { id: true, taskId: true, createdAt: true, attempts: true } }); if (existing) return { id: existing.id, taskId: existing.taskId, createdAt: existing.createdAt.getTime(), attempts: existing.attempts }; const job = await db.taskQueueJob.create({ data: { taskId: task.id, tenantId: task.tenantId, status: "QUEUED", attempts: 0 } }); return { id: job.id, taskId: job.taskId, createdAt: job.createdAt.getTime(), attempts: job.attempts }; }
  async dequeue(): Promise<QueueJob | null> { const job = await db.taskQueueJob.findFirst({ where: { status: "QUEUED" }, orderBy: { createdAt: "asc" } }); if (!job) return null; const claimed = await db.taskQueueJob.updateMany({ where: { id: job.id, status: "QUEUED" }, data: { status: "RUNNING", attempts: { increment: 1 }, startedAt: new Date() } }); if (claimed.count !== 1) return null; return { id: job.id, taskId: job.taskId, createdAt: job.createdAt.getTime(), attempts: job.attempts + 1 }; }
  async complete(jobId: string): Promise<void> { await db.taskQueueJob.updateMany({ where: { id: jobId, status: "RUNNING" }, data: { status: "COMPLETED", finishedAt: new Date(), error: null } }); }
  async fail(jobId: string, error: string): Promise<void> { await db.taskQueueJob.updateMany({ where: { id: jobId, status: "RUNNING" }, data: { status: "FAILED", finishedAt: new Date(), error: error.slice(0, 4000) } }); }
  async recoverStale(maxAgeMs: number): Promise<number> { const cutoff = new Date(Date.now() - maxAgeMs); const result = await db.taskQueueJob.updateMany({ where: { status: "RUNNING", startedAt: { lt: cutoff } }, data: { status: "QUEUED", startedAt: null } }); return result.count; }
  async size(): Promise<number> { return db.taskQueueJob.count({ where: { status: "QUEUED" } }); }
  async clear(): Promise<void> { await db.taskQueueJob.deleteMany({ where: { status: "QUEUED" } }); }
}
